services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MySecret123
      POSTGRES_DB: udemy-nodejs-course-hc-auth-session
    ports:
      - 5433:5432
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
